name: Beyond
favicon: null
layout_spectrum: 0.19945712154731154
typography_spectrum: 0.293257397133857
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2335317621473223
  lightness: 0.45543707092292607
  saturation: 0.4505117181688547
  rhythmicContrast: 0.6490947192069143
purpose: []
